### ISSUE TITLE
an error in `model_stage1.train`

### ISSUE THREAD

**Issue by fengweimin-maker** [SydneyBioX/scJoint#5]
Hi, authors,
     I got an error when I ran `python3 main.py`,just like the follow. I am confused of this problem,I would appreciate it if you could reply to me soon, Thanks!!
![image](https://user-images.githubusercontent.com/60514168/159151694-0508fec1-0293-4af9-a22c-5e5cb8a5e060.png)

**Comment by YingxinLin** [comment]
Hi,

It could be due to input file format... would you like to download the data from this [link](http://www.maths.usyd.edu.au/u/yingxinl/wwwnb/scJoint/data_10x.zip) for the 10x example data.

Yingxin

**Comment by fengweimin-maker** [comment]
> Hi,
> 
> It could be due to input file format... would you like to download the data from this [link](http://www.maths.usyd.edu.au/u/yingxinl/wwwnb/scJoint/data_10x.zip) for the 10x example data.
> 
> Yingxin

Hi,
Sorry, I can't download the 10x example data for it closed when I clicked it.
